'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import { useSearchParams } from 'next/navigation';
import {
  Save,
  ClipboardList,
  Loader2,
  Palette,
  Image,
  Gift,
  ToggleLeft,
  ToggleRight,
  Sparkles,
  ArrowLeft,
  ImageIcon,
  Building2,
} from 'lucide-react';
import { Question, type RewardType } from './types';
import { saveSurvey, fetchSurveyById } from '@/actions/survey';
import EditorPanel from './EditorPanel';
import LivePreview from './LivePreview';

const REWARD_LABELS: Record<RewardType, string> = {
  none: 'Ninguno',
  discount: 'Descuento Directo',
  giveaway: 'Sorteo / Regalo',
};

const normalizeQuestionType = (t: string): Question['type'] => {
  if (!t) return 'text_open';
  const raw = t.toLowerCase().trim();
  const mapper: Record<string, Question['type']> = {
    'stars': 'rating_stars',
    'star_rating': 'rating_stars',
    'rating': 'rating_stars',
    'rating_stars': 'rating_stars',
    'nps': 'nps',
    'single': 'single_choice',
    'single_choice': 'single_choice',
    'multiple': 'multiple_choice',
    'multiple_choice': 'multiple_choice',
    'options': 'single_choice',
    'text': 'text_open',
    'open_text': 'text_open',
    'text_open': 'text_open',
    'open': 'text_open',
    'likert': 'likert',
    'linear': 'linear_scale',
    'linear_scale': 'linear_scale',
    'csat': 'csat'
  };
  return mapper[raw] || 'text_open';
};

export default function SurveyBuilder() {
  const [surveyTitle, setSurveyTitle] = useState('');
  const [surveyDescription, setSurveyDescription] = useState('');
  const [company, setCompany] = useState('');
  const [questions, setQuestions] = useState<Question[]>([]);
  const [primaryColor, setPrimaryColor] = useState('#6366f1');
  const [logoUrl, setLogoUrl] = useState('');
  const [coverImageUrl, setCoverImageUrl] = useState('');

  // Reward state
  const [rewardType, setRewardType] = useState<RewardType>('none');
  const [rewardText, setRewardText] = useState('');
  const [rewardImageUrl, setRewardImageUrl] = useState('');
  const [requireContact, setRequireContact] = useState(false);

  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);

  // AI generation state
  const [aiPrompt, setAiPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [aiError, setAiError] = useState<string | null>(null);
  const hasAutoGenerated = useRef(false);
  const searchParams = useSearchParams();
  const surveyIdParam = searchParams.get('id');

  const [isLoadingSurvey, setIsLoadingSurvey] = useState(false);

  useEffect(() => {
    async function loadSurvey() {
      if (!surveyIdParam) return;
      setIsLoadingSurvey(true);
      const { data, error } = await fetchSurveyById(surveyIdParam);
      if (data) {
        setSurveyTitle(data.title);
        setSurveyDescription(data.description || '');
        setCompany(data.company || '');
        setPrimaryColor(data.primary_color);
        setLogoUrl(data.logo_url || '');
        setCoverImageUrl(data.cover_image_url || '');
        setRewardType(data.reward_type as RewardType);
        setRewardText(data.reward_text || '');
        setRewardImageUrl(data.reward_image_url || '');
        setRequireContact(data.require_contact);
        setQuestions(
          data.questions.map((q) => ({
            id: q.id,
            title: q.title,
            type: q.type as any,
            isRequired: q.is_required,
            options: q.options || undefined,
            scaleMax: (q.scaleMax as 7 | 10) || 10,
          }))
        );
      }
      setIsLoadingSurvey(false);
    }
    loadSurvey();
  }, [surveyIdParam]);

  const handleSave = async () => {
    if (!surveyTitle.trim()) return;
    setSaving(true);
    setSaveError(null);

    // 🕵️‍♂️ AGREGA ESTO PARA DEPURAR:
    const preguntasAEnviar = questions.map((q) => ({
      id: q.id,
      title: q.title,
      type: q.type,
      isRequired: q.isRequired,
      options: q.options,
      scaleMax: q.scaleMax || 10,
    }));
    console.log("ENVIANDO AL SERVIDOR:", preguntasAEnviar);

      const result = await saveSurvey(
        {
          id: surveyIdParam || undefined,
          title: surveyTitle,
          description: surveyDescription,
          company: company.trim() || undefined,
          primaryColor,
        logoUrl: logoUrl || undefined,
        coverImageUrl: coverImageUrl || undefined,
        rewardType,
        rewardText: rewardText || undefined,
        rewardImageUrl: rewardImageUrl || undefined,
        requireContact,
      },
      questions.map((q) => ({
        id: q.id,
        title: q.title,
        type: q.type,
        isRequired: q.isRequired,
        options: q.options,
        scaleMax: q.scaleMax || 10,
      }))
    );

    setSaving(false);

    if (result.success) {
      setSaved(true);
      setTimeout(() => setSaved(false), 2500);
    } else {
      setSaveError(result.error);
      setTimeout(() => setSaveError(null), 4000);
    }
  };

  const handleGenerate = useCallback(async (overridePrompt?: string) => {
    const text = overridePrompt ?? aiPrompt;
    if (!text.trim() || isGenerating) return;
    setAiPrompt(text);
    setIsGenerating(true);
    setAiError(null);

    try {
      const res = await fetch('/api/generate-survey', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: text.trim() }),
      });

      const data = await res.json();

      if (!res.ok || !data.questions) {
        setAiError(data.error || 'Error al generar la encuesta.');
        setIsGenerating(false);
        return;
      }

      const generated: Question[] = data.questions.map((q: Record<string, unknown>) => ({
        id: crypto.randomUUID(),
        title: (q.title as string) || '',
        type: normalizeQuestionType(q.type as string),
        options: Array.isArray(q.options) ? (q.options as string[]) : undefined,
        isRequired: Boolean(q.isRequired),
      }));

      setQuestions(generated);

      // Auto-fill title from the prompt if empty
      const words = text.trim().split(' ').slice(0, 6).join(' ');
      setSurveyTitle((prev) => prev.trim() ? prev : words.charAt(0).toUpperCase() + words.slice(1));
    } catch {
      setAiError('Error de conexión. Verifica tu API key.');
    }

    setIsGenerating(false);
  }, [aiPrompt, isGenerating]);

  // Session Storage Loader (JSON Import)
  useEffect(() => {
    const draft = sessionStorage.getItem('surveyDraft');
    if (draft && !surveyIdParam && !hasAutoGenerated.current) {
      try {
        const parsed = JSON.parse(draft);
        if (parsed.title) setSurveyTitle(parsed.title);
        if (parsed.description) setSurveyDescription(parsed.description);
        if (parsed.primary_color) setPrimaryColor(parsed.primary_color);
        if (parsed.questions && Array.isArray(parsed.questions)) {
          setQuestions(
            parsed.questions.map((q: any) => ({
              id: crypto.randomUUID(), // Ignoramos el id del JSON para evitar errores de tipo UUID en BD
              title: q.title || '',
              type: normalizeQuestionType(q.type),
              isRequired: q.isRequired || q.is_required || false,
              options: Array.isArray(q.options) ? q.options : undefined,
              scaleMax: q.scaleMax || q.scale_max || 10,
            }))
          );
        }
        sessionStorage.removeItem('surveyDraft');
        hasAutoGenerated.current = true; // prevent ?prompt from overriding
      } catch (e) {
        console.error('Error parsing survey draft:', e);
      }
    }
  }, [surveyIdParam]);

  // Auto-generate from URL ?prompt=...
  useEffect(() => {
    const urlPrompt = searchParams.get('prompt');
    if (urlPrompt && !hasAutoGenerated.current && !surveyIdParam) {
      hasAutoGenerated.current = true;
      handleGenerate(urlPrompt);
    }
  }, [searchParams, handleGenerate, surveyIdParam]);

  if (isLoadingSurvey) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-slate-50">
        <Loader2 size={32} className="animate-spin text-indigo-600" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50">
      {/* ── Top Bar ────────────────────────────────────── */}
      <header className="sticky top-0 z-30 border-b border-slate-200 bg-white/80 backdrop-blur-lg">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6 lg:px-8">
          <div className="flex items-center gap-4">
            <button
              onClick={() => window.location.href = '/admin'}
              className="flex items-center justify-center rounded-lg p-2 text-slate-500 transition-colors hover:bg-slate-100 hover:text-slate-800"
              title="Volver al Dashboard"
            >
              <ArrowLeft size={20} />
            </button>
            <div className="flex items-center gap-3">
              <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-gradient-to-br from-indigo-600 to-violet-600 shadow-sm">
                <ClipboardList size={18} className="text-white" />
              </div>
              <div>
                <h1 className="text-base font-bold text-slate-800">Crear Encuesta</h1>
                <p className="text-xs text-slate-500">
                  {questions.length} {questions.length === 1 ? 'pregunta' : 'preguntas'}
                </p>
              </div>
            </div>
          </div>
          <button
            type="button"
            onClick={handleSave}
            disabled={saving}
            className={`flex items-center gap-2 rounded-lg px-5 py-2.5 text-sm font-semibold shadow-sm transition-all ${saved
              ? 'bg-emerald-600 text-white'
              : saveError
                ? 'bg-red-600 text-white'
                : 'bg-gradient-to-r from-indigo-600 to-violet-600 text-white hover:shadow-md hover:brightness-110 disabled:opacity-70'
              }`}
          >
            {saving ? (
              <><Loader2 size={16} className="animate-spin" /> Guardando...</>
            ) : saved ? (
              <><Save size={16} /> ¡Guardado!</>
            ) : saveError ? (
              <>{saveError}</>
            ) : (
              <><Save size={16} /> Guardar encuesta</>
            )}
          </button>
        </div>
      </header>

      {/* ── Two Column Layout ──────────────────────────── */}
      <main className="mx-auto grid max-w-7xl gap-8 px-4 py-8 sm:px-6 lg:grid-cols-[1fr_420px] lg:px-8">
        {/* Editor */}
        <section className="space-y-6">
          {/* ── AI Generation ──────────────────────────── */}
          <div className="rounded-2xl bg-gradient-to-r from-violet-50 to-indigo-50 p-5 ring-1 ring-indigo-100">
            <div className="mb-3 flex items-center gap-2">
              <Sparkles size={18} className="text-indigo-600" />
              <h2 className="text-sm font-bold text-slate-800">Generar con IA</h2>
            </div>
            <div className="flex gap-2">
              <input
                type="text"
                value={aiPrompt}
                onChange={(e) => { setAiPrompt(e.target.value); setAiError(null); }}
                placeholder="Ej: Encuesta para evaluar el menú de un café..."
                className="flex-1 rounded-xl border border-indigo-200 bg-white px-4 py-2.5 text-sm text-slate-700 outline-none placeholder:text-slate-400 focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100"
                onKeyDown={(e) => { if (e.key === 'Enter') handleGenerate(); }}
              />
              <button
                type="button"
                onClick={() => handleGenerate()}
                disabled={isGenerating || !aiPrompt.trim()}
                className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-indigo-600 to-violet-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition-all hover:shadow-md hover:brightness-110 disabled:opacity-60"
              >
                {isGenerating ? (
                  <><Loader2 size={14} className="animate-spin" /> Generando...</>
                ) : (
                  <><Sparkles size={14} /> Generar con IA</>
                )}
              </button>
            </div>
            {aiError && (
              <p className="mt-2 text-xs font-medium text-red-500">{aiError}</p>
            )}
          </div>

          <EditorPanel
            surveyTitle={surveyTitle}
            surveyDescription={surveyDescription}
            questions={questions}
            onSurveyTitleChange={setSurveyTitle}
            onSurveyDescriptionChange={setSurveyDescription}
            onQuestionsChange={setQuestions}
          />

          {/* ── Configuración Comercial ─────────────────── */}
          <div className="rounded-2xl bg-white p-5 shadow-sm">
            <div className="mb-4 flex items-center gap-2">
              <Building2 size={18} className="text-blue-600" />
              <h2 className="text-sm font-bold text-slate-800">Configuración Comercial</h2>
            </div>
            
            <div>
              <label className="mb-1.5 block text-xs font-medium text-slate-600">Nombre de la Empresa Comercial / Cliente</label>
              <input
                type="text"
                value={company}
                onChange={(e) => setCompany(e.target.value)}
                placeholder="Ej: ACME Corp, Coca-Cola, etc..."
                className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-700 outline-none placeholder:text-slate-400 focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100"
              />
              <p className="mt-1.5 text-[11px] text-slate-400">Este nombre te ayudará a organizar y encontrar la encuesta más rápido dentro de tu panel de administración.</p>
            </div>
          </div>

          {/* ── Design Section ───────────────────────────── */}
          <div className="rounded-2xl bg-white p-5 shadow-sm">
            <div className="mb-4 flex items-center gap-2">
              <Palette size={18} className="text-violet-600" />
              <h2 className="text-sm font-bold text-slate-800">Diseño y Apariencia</h2>
            </div>
            <div className="grid gap-4 sm:grid-cols-2">
              <div>
                <label className="mb-1.5 block text-xs font-medium text-slate-600">Color principal</label>
                <div className="flex items-center gap-3">
                  <input
                    type="color"
                    value={primaryColor}
                    onChange={(e) => setPrimaryColor(e.target.value)}
                    className="h-10 w-14 cursor-pointer rounded-lg border border-slate-200"
                  />
                  <input
                    type="text"
                    value={primaryColor}
                    onChange={(e) => setPrimaryColor(e.target.value)}
                    className="flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-700 uppercase tracking-wider outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100"
                  />
                </div>
              </div>
              <div>
                <label className="mb-1.5 block text-xs font-medium text-slate-600">URL del Logo (Opcional)</label>
                <div className="flex items-center gap-2">
                  <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-lg border border-slate-200 bg-slate-50">
                    {logoUrl ? (
                      <img
                        src={logoUrl}
                        alt="Logo"
                        className="h-7 w-7 rounded object-contain"
                        onError={(e) => { (e.target as HTMLImageElement).style.display = 'none'; }}
                      />
                    ) : (
                      <Image size={16} className="text-slate-400" />
                    )}
                  </div>
                  <input
                    type="text"
                    value={logoUrl}
                    onChange={(e) => setLogoUrl(e.target.value)}
                    placeholder="https://ejemplo.com/logo.png"
                    className="flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-700 outline-none placeholder:text-slate-400 focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100"
                  />
                </div>
              </div>
            </div>

            <div className="mt-4">
              <label className="mb-1.5 block text-xs font-medium text-slate-600">URL de Imagen de Portada (Banner opcional debajo del título)</label>
              <div className="flex items-center gap-2">
                <div className="flex h-10 w-14 flex-shrink-0 items-center justify-center rounded-lg border border-slate-200 bg-slate-50 overflow-hidden">
                  {coverImageUrl ? (
                    <img
                      src={coverImageUrl}
                      alt="Cover"
                      className="h-full w-full object-cover"
                      onError={(e) => { (e.target as HTMLImageElement).style.display = 'none'; }}
                    />
                  ) : (
                    <ImageIcon size={16} className="text-slate-400" />
                  )}
                </div>
                <input
                  type="text"
                  value={coverImageUrl}
                  onChange={(e) => setCoverImageUrl(e.target.value)}
                  placeholder="https://ejemplo.com/banner.jpg"
                  className="flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-700 outline-none placeholder:text-slate-400 focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100"
                />
              </div>
            </div>
          </div>

          {/* ── Reward Section ────────────────────────────── */}
          <div className="rounded-2xl bg-white p-5 shadow-sm">
            <div className="mb-4 flex items-center gap-2">
              <Gift size={18} className="text-amber-500" />
              <h2 className="text-sm font-bold text-slate-800">Premio al finalizar</h2>
            </div>

            {/* Reward type selector */}
            <div className="mb-4">
              <label className="mb-1.5 block text-xs font-medium text-slate-600">Tipo de premio</label>
              <div className="flex gap-2">
                {(Object.keys(REWARD_LABELS) as RewardType[]).map((rt) => (
                  <button
                    key={rt}
                    type="button"
                    onClick={() => setRewardType(rt)}
                    className={`rounded-lg border px-4 py-2 text-xs font-semibold transition-all ${rewardType === rt
                      ? 'border-amber-400 bg-amber-50 text-amber-700 shadow-sm'
                      : 'border-slate-200 bg-white text-slate-600 hover:bg-slate-50'
                      }`}
                  >
                    {REWARD_LABELS[rt]}
                  </button>
                ))}
              </div>
            </div>

            {rewardType !== 'none' && (
              <div className="space-y-4 border-t border-slate-100 pt-4">
                {/* Reward text */}
                <div>
                  <label className="mb-1.5 block text-xs font-medium text-slate-600">
                    Texto del premio
                  </label>
                  <input
                    type="text"
                    value={rewardText}
                    onChange={(e) => setRewardText(e.target.value)}
                    placeholder="Ej: ¡Ganaste un postre gratis!"
                    className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-700 outline-none placeholder:text-slate-400 focus:border-amber-400 focus:ring-2 focus:ring-amber-100"
                  />
                </div>

                {/* Reward image */}
                <div>
                  <label className="mb-1.5 block text-xs font-medium text-slate-600">
                    URL de imagen persuasiva
                  </label>
                  <div className="flex items-center gap-2">
                    {rewardImageUrl && (
                      <img
                        src={rewardImageUrl}
                        alt=""
                        className="h-10 w-10 rounded-lg border border-slate-200 object-cover"
                        onError={(e) => { (e.target as HTMLImageElement).style.display = 'none'; }}
                      />
                    )}
                    <input
                      type="text"
                      value={rewardImageUrl}
                      onChange={(e) => setRewardImageUrl(e.target.value)}
                      placeholder="https://ejemplo.com/reward.jpg"
                      className="flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-700 outline-none placeholder:text-slate-400 focus:border-amber-400 focus:ring-2 focus:ring-amber-100"
                    />
                  </div>
                </div>

                {/* Require contact toggle */}
                <div className="flex items-center justify-between rounded-lg border border-slate-200 bg-slate-50 px-4 py-3">
                  <div>
                    <p className="text-sm font-medium text-slate-700">
                      Pedir WhatsApp / Email
                    </p>
                    <p className="text-xs text-slate-400">
                      El cliente debe dejar su contacto para reclamar
                    </p>
                  </div>
                  <button
                    type="button"
                    onClick={() => setRequireContact(!requireContact)}
                    className="text-slate-400 transition-colors"
                  >
                    {requireContact ? (
                      <ToggleRight size={32} className="text-amber-500" />
                    ) : (
                      <ToggleLeft size={32} />
                    )}
                  </button>
                </div>
              </div>
            )}
          </div>
        </section>

        {/* Live Preview */}
        <aside>
          <LivePreview
            surveyTitle={surveyTitle}
            surveyDescription={surveyDescription}
            questions={questions}
            primaryColor={primaryColor}
            logoUrl={logoUrl}
            coverImageUrl={coverImageUrl}
          />
        </aside>
      </main>
    </div>
  );
}
